### ISSUE TITLE
Coordination Numbers and Spheres or Setup and Installation page. 

### ISSUE THREAD

**Issue by Sulstice** [f3rmion/gitbook-kallisto#18]
Leave a reminder for folk to activate their environment into the current shell in the page before you reach your sub commands. 

I've got a plethora of python envs on my stuff and everyone runs stuff differently. If I run your program directly, you will achieve a place for no entry points. If you want an entry point this way then let me know :). 

```

No module named kallisto.__main__; 'kallisto' is a package and cannot be directly executed

```

Some people...idk why...will see one error and move on.

So a suggested note would be something simple or however to add into the docs. 

```

source activate env

```

**Comment by f3rmion** [comment]
Hi @Sulstice,

> Some people...idk why...will see one error and move on.
> 
> So a suggested note would be something simple or however to add into the docs.
> 
> ```
> 
> source activate env
> ```
Users should look critically at their own work and think along, especially when working in a scientific environment.  An additional hint that the user must activate his virtual environment before using ``kallisto`` is an overkill in my opinion.

> I've got a plethora of python envs on my stuff and everyone runs stuff differently. If I run your program directly, you will achieve a place for no entry points. If you want an entry point this way then let me know :).

Contributions to ``kallisto`` are always welcome! We can definitely chat about upcoming features ;)

**Comment by f3rmion** [comment]
> yeah lets do that instead - i like that idea. Let me take care of some things with both PIs and I can contribute some entry point code :). Ill open up an issue on your repo for myself so i dont forget. Is that alright?

Sounds great, just open a feature request and add some explanation about what you want, how you want to code it etc.

**Comment by f3rmion** [comment]
OK, I think this can be closed :)

**Comment by RMeli** [comment]
> An additional hint that the user must activate his virtual environment before using kallisto is an overkill in my opinion.

I agree with this point; additionally, different users will manage different environments in different ways, so I think it will just add confusion.
