### ISSUE TITLE
Electronegativity Equilibration References & Explanations

### ISSUE THREAD

**Issue by Sulstice** [f3rmion/gitbook-kallisto#19]
Formula here is nuts. 

This is a new formula for me and it isn't as obvious as you might perhaps believe. 

<img width="682" alt="Screen Shot 2021-03-07 at 10 45 09 AM" src="https://user-images.githubusercontent.com/11812946/110245670-36d5b680-7f32-11eb-9db3-1a0ad3363a23.png">

I would like a reference here but maybe a better explanation into the formula. 

The `Lagrangian optimisation`, however, I do know this application for solving variables. Again another reference here for how this works is needed or perhaps your own explanation in your own words. Take your pic. 

Overall five parameter exist per element: Jii, gammaii, ENi, Rcovi, and kappa

I need to know what each of these things represent in common english or whatever language (as long as I can translate it).

**Comment by f3rmion** [comment]
Fair enough, maybe I should dig a little deeper into the topic and explain the theory behind the scenes for this formula as well.
