### ISSUE TITLE
Sterimol Descriptors

### ISSUE THREAD

**Issue by Sulstice** [f3rmion/gitbook-kallisto#20]
I need to clarify some things:

So I'm playing around with the `origin` and the `partner` parameter. Here are you sayin the origin is the atom number and is that read in line by line into the file? So for example:

```
C     2.081440     0.615100    -0.508430
C     2.742230     1.824030    -1.200820
N     4.117790     1.799870    -1.190410
C     4.943570     2.827040    -1.822060
C     6.440080     2.569360    -1.637600
O     7.351600     3.252270    -2.069090
```

In this case the first row `C  2.081440     0.615100    -0.508430` is origin 1? And then for partner I extended it all the way to max value which means this is the last element right so O?

that way I can pass in

```

kallisto --verbose stm --inp test.xyz --origin 1 --partner 6

```

What might be nice is to have the `origin` and the `partner` outputted to the console or what atoms they are to give confidence to the user that the program has selected the right atoms.

**Comment by f3rmion** [comment]
OK, I'm not sure if I totally understood your point here.

The Sterimol parameters ([GitHub](https://github.com/bobbypaton/wSterimol) and [ACS](https://pubs.acs.org/doi/10.1021/acscatal.8b04043)) represent the sterics of a given molecule with respect to a covalent bound defined by the aufpunkt (origin) and its partner. In the docs, it is noted that the numbering starts always at ``0`` (see "Define the subcommand").

```bash
# Note that the atom count starts at 0
--origin <int>
(required)
description:
 number of the origin atom

# Note that the atom count starts at 0
--partner <int>
(required)
description:
 number of the partner atom
```

So the first atom of your input ``C     2.081440     0.615100    -0.508430`` would have index 0.

> What might be nice is to have the origin and the partner outputted to the console or what atoms they are to give confidence to the user that the program has selected the right atoms.

We could consider adding the indices of the atoms to the default output as well.

**Comment by Sulstice** [comment]
ah yeah, I think that actually might help me. I think the point I was trying to make is if I ran this on a bigger system it might be nice to have the atom index maybe as an optional flag but yeah this is not necessary because then I have to scroll through (but thats just me as a user). 

Perhaps just an addition. But I know you have tests and other things perhaps tied to it so only if you have time.

**Comment by f3rmion** [comment]
Hi @Sulstice,

I added to index of both the origin and the partner atom to the ``stm`` output.
