### ISSUE TITLE
Breadth First Sorting Visual Confusion

### ISSUE THREAD

**Issue by Sulstice** [f3rmion/gitbook-kallisto#21]
This is very cool but damn do I need a visual depiction here of what just happened. When I ran it on the alanine-glycine example:

**Unsorted Data**

```
  20

C     2.081440     0.615100    -0.508430
C     2.742230     1.824030    -1.200820
N     4.117790     1.799870    -1.190410
C     4.943570     2.827040    -1.822060
C     6.440080     2.569360    -1.637600
O     7.351600     3.252270    -2.069090
N     0.610100     0.695090    -0.538780
O     2.095560     2.724940    -1.739670
O     6.705220     1.463410    -0.897460
H     0.303080     1.426060     0.103770
H     0.338420     1.050680    -1.460480
C     2.488753    -0.593400    -1.198448
H     2.416500     0.557400     0.532050
H     4.614100     1.081980    -0.670550
H     4.699850     3.794460    -1.373720
H     4.722890     2.844690    -2.894180
H     7.687400     1.448620    -0.860340
H     2.029201    -1.457008    -0.719999
H     2.170233    -0.542411    -2.238576
H     3.572730    -0.688405    -1.154998
```

Command: `kallisto sort --inp test.xyz --start 0 > test_s.xyz`

```
   20

Created with kallisto
C      2.0814    0.6151   -0.5084
C      2.7422    1.8240   -1.2008
N      0.6101    0.6951   -0.5388
C      2.4888   -0.5934   -1.1984
H      2.4165    0.5574    0.5321
N      4.1178    1.7999   -1.1904
O      2.0956    2.7249   -1.7397
H      0.3031    1.4261    0.1038
H      0.3384    1.0507   -1.4605
H      2.0292   -1.4570   -0.7200
H      2.1702   -0.5424   -2.2386
H      3.5727   -0.6884   -1.1550
C      4.9436    2.8270   -1.8221
H      4.6141    1.0820   -0.6705
C      6.4401    2.5694   -1.6376
H      4.6998    3.7945   -1.3737
H      4.7229    2.8447   -2.8942
O      7.3516    3.2523   -2.0691
O      6.7052    1.4634   -0.8975
H      7.6874    1.4486   -0.8603

```

A visual depiction would be super nice to have to see how it reassigned. Because now I have to trust that your code did it correctly (and there's always weird bugs) so I need a validation. How did you generate the circles? or draw them manually?

Also, no offense, I don't like this in the output: `Created with kallisto`. I will reference you but sometimes when I am parsing output into another program it's annoying to deal with stuff like this.

**Comment by Sulstice** [comment]
I actually think the RDKit component would be nice here to visualize the structures but the dependencies for RDKit then turn into a conda env problem. 

Perhaps the `IndigoRenderer` code which is pure python can be a possible avenue.

**Comment by Sulstice** [comment]
Huh, that is very interesting tool. I like the visuals and it produced really nice pictures. Can you include that in the documentation? I think people would like to see that as well. You can more or less copy/paste what you wrote haha. 

Looking at the ASE in a little more in-depth how did they actually sort it I can guess from looking - carbons, nitros, oxygen, hydrogens. Long chain first then evaluate connections 

```
    if tags is None:
        tags = atoms.get_chemical_symbols()
    else:
        tags = list(tags)
    deco = sorted([(tag, i) for i, tag in enumerate(tags)])

```

no way this was is it?

One thing a reviewer on here taught me - was to put things like this in jupyter notebooks. But they suck to distribute - awful to read. So for a passerby of the code I've actually deployed into google colab for the older generation to keep up. 

If you want that type of code let me know. 

But I believe just writing it in the documentation with the peptide example is actually pretty cool and sufficient.

**Comment by f3rmion** [comment]
Hi @Sulstice,

I added the alanine-glycine example to the BFS section.

> Looking at the ASE in a little more in-depth how did they actually sort it I can guess from looking - carbons, nitros, oxygen, hydrogens. Long chain first then evaluate connections

Do you mean how they number the structure in the GUI? This is directly related to the occurrence in the ``xmol`` file.

**Comment by f3rmion** [comment]
OK, I guess this can be closed. BFS section has been drastically improved by incorporating another example :)

**Comment by Sulstice** [comment]
Yes! I read your examples! This is very cool code.
